language: c

cache: apt

install:
    - echo "starting texlive install at `date`"
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - sudo apt-get install chktex latex2html
    - echo "finished texlive install at `date`"
    - mkdir build

script:
    - cd build && cmake ../ && make
    - chktex -W # Print version information.
    - chktex -q -n 1 -n 8 -n 36 *.tex ch-*/*.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    - test ! -s lint.out
    - (grep -i undefine thesis.log; if [ "$?" -ne "1" ]; then echo "Undefined refrences exist, or error parsing thesis.log" && false; else true; fi)
